CREATE DATABASE GESTION
GO
USE GESTION -- no olvidarse nunca de seleccionar la BD de trabajo
GO
CREATE TABLE PROPIETARIOS
 (DNI CHAR(10) NOT NULL CONSTRAINT pk_prop PRIMARY KEY,
 NOMBRE CHAR(25) NOT NULL,
 DIRECCION CHAR(30));
CREATE TABLE LOCALES
 (CODIGO CHAR(5) NOT NULL CONSTRAINT pk_loc PRIMARY KEY,
 DNI CHAR(10) NOT NULL,
 UBICACIÓN CHAR(4) NOT NULL,
 SUPERFICIE DEC(8,2) NOT NULL,
 CONSTRAINT fk_loc FOREIGN KEY ( DNI ) REFERENCES PROPIETARIOS ( DNI )); 
 
 
 
 USE GESTION
GO
INSERT INTO PROPIETARIOS (DNI, NOMBRE, DIRECCION)
 VALUES ('13234567R', 'Sanz, Luis', 'Gran Vía 26')
GO

INSERT INTO LOCALES (CODIGO,DNI,UBICACIÓN,SUPERFICIE)
VALUES ('L-234', '13234567R','MAD',100)
GO
SELECT CODIGO, UBICACIóN, NOMBRE, DIRECCION
 FROM LOCALES, PROPIETARIOS
WHERE LOCALES.DNI = PROPIETARIOS.DNI AND
 SUPERFICIE < 200
GO
UPDATE PROPIETARIOS SET DIRECCION ='Alta 87'
 WHERE DNI = '13234567R'
 Go 